### ISSUE TITLE
Ping lib using a switch 

### ISSUE THREAD

**Issue by avilesmi** [HPENetworking/topology_lib_ping#1]
Ping lib does not support other object than a host, if you use openswitch objects for example:
packets = 5
ping1 = **ops1**.libs.ping.ping(packets, '10.0.1.1')

An exception is raised : 
**"Exception: Could not parse ping result"**

**Comment by saenzpa** [comment]
As we discussed, ping for switch is not part of this library, as it is part of vtysh. Closing as this is being targeted in this pull request:
https://github-sc-p.corp.hp.com/hpe-networking/topology_lib_vtysh/pull/33

**Comment by pablo-araya-hpe** [comment]
Miguel, as you need a issue ID to point the missing part of one test I would suggest to move this one to vtysh repo and remove it as soon as the pull request gets done.
